### ISSUE TITLE
Error compiling when running

### ISSUE THREAD

**Issue by evanlu14** [weaknetlabs/libpcap-80211-c#1]
Hello, thanks for sharing your code. It helps, but when I run the code, seems `pcap_compile()` part fails.
My operating system is Ubuntu16.04, and my gcc version is 5.4.0
Can you help me?

```
lzc@ubuntu:~/Workspace/Git/libpcap-80211-c$ sudo gcc 802sniff.c -lpcap -o 80211sniff -ggdb
lzc@ubuntu:~/Workspace/Git/libpcap-80211-c$ sudo ./80211sniff wlan0
Error compiling Libpcap filter, type mgt subtype beacon
Error setting Libpcap filter, type mgt subtype beacon
RSSI: -208 dBm
AP Frequency: 1030Mhz
ESSID length: 0 bytes.
ESSID string: 
BSSID string: 80:00:00:00:72:7B

```

**Comment by RackunSec** [comment]
Hello, I have never seen this error before. Have you modified the code before compiling? Can you try to recompile without the GNU Debugging symbols? What version of Libpcap are you using? According to the Libpcap (TCPDump) developer site: (http://www.tcpdump.org/manpages/pcap-filter.7.html), the filter, "_If the specified wlan_type is mgt, then valid wlan_subtypes are: assoc-req, assoc-resp, reassoc-req, reassoc-resp, probe-req, probe-resp, beacon, atim, disassoc, auth and deauth._" is correct.

**Comment by evanlu14** [comment]
Hello, I did not change the code. And recompiling without the debugging symbols, the result is the same. And my Libpcap version is 0.8

**Comment by RackunSec** [comment]
I wonder if that may be the cause of the issue. Whey are you using such an old version? Id that part of the Ubuntu package manager? It looks like that version ended in 2012 (http://www.tcpdump.org/release/). I am using version 1.7.4 in Weakerthan Linux. Can you try a newer version of libpcap for me? I'd like to find out why exactly you get this warning.

**Comment by RackunSec** [comment]
Can you try the pcap_geterr()  or  pcap_perror() functions to possibly show what exactly went wrong in the calls to pcap_compile() and pcap_setFilter() ? This may give us more clues!

**Comment by RackunSec** [comment]
Oh, and you'll have to pass handle to those functions also, here is a simple usage: http://linux.die.net/man/3/pcap_geterr They print to stderr text strings. Thanks!

**Comment by evanlu14** [comment]
Thanks. I add one line to the code 

```
if(pcap_compile(handle,&fp,filter,0,netp)==-1) {// -1 means failed
    fprintf(stderr,"Error compiling Libpcap filter, %s\n",filter);
    fprintf ("%s\n", pcap_geterr (handle));
}
if(pcap_setfilter(handle,&fp)==-1) // -1 means failed - but we don't exit(1)
    fprintf(stderr,"Error setting Libpcap filter, %s\n",filter); // same as above

```

and now the result is 

```
lzc@ubuntu:~/Workspace/Git/libpcap-80211-c$ sudo ./a.out wlan0
Error compiling Libpcap filter, type mgt subtype beacon
802.11 link-layer types supported only on 802.11
Error setting Libpcap filter, type mgt subtype beacon
```

I am trying to upgrade my Libpcap now. And I am also wondering whether I should change my wireless card to moniter mode, will this cause the problem?

**Comment by RackunSec** [comment]
Yes! absolutely- that should help! I always use RFMON using airmon-ng to start the device in montor mode.

**Comment by evanlu14** [comment]
It seems my laptop wireless card is incompatible with the airmon-ng and I can not start the device in monitor mode. 
And finally I bought a new USB wireless card and problem solved! 
Thanks for suggestions and codes!

**Comment by RackunSec** [comment]
Ah, that's great news! If you have any more issues in the future, I'd be glad to help!

**Comment by RackunSec** [comment]
Issue is resolved!
