### ISSUE TITLE
how to get ESSID string 

### ISSUE THREAD

**Issue by yashashree-88** [weaknetlabs/libpcap-80211-c#2]
Hello I want to print ssid for 802.11 frame....I can  able to execute program but  I can't able to get ESSID string

sudo ./80211sniff wlxb4b024bcc16e
RSSI: -1 dBm
AP Frequency: 128Mhz
ESSID length: 95 bytes.
ESSID string: 936B
BSSID string: 0C:F0:43:23:B9:03

Kindly help me out.

Thank you.

**Comment by yashashree-88** [comment]
I fixed issue 

just replace below line with now I can access complete ssid

	essid = packet + 56; // store the ESSID/Router name too

Thank you

**Comment by RackunSec** [comment]
Thanks!
